Repository TeamDon-tBe/ANDROID, pull requests merged in 2024-06, with the labels that each got.

#272 [Feature/#264] : 푸시알림 구현, 신고하기 api 연결
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamdontbe/dontbe/DontBeApp.kt
  app/src/main/java/com/teamdontbe/dontbe/service/DontBeFirebaseMessagingService.kt
  build-logic/build.gradle.kts
  build-logic/src/main/java/com/teamdontbe/dontbe/plugin/AndroidApplicationPlugin.kt
  build-logic/src/main/java/com/teamdontbe/dontbe/plugin/CommonConfigs.kt
  build-logic/src/main/java/com/teamdontbe/dontbe/plugin/GoogleFirebasePlugin.kt
  build.gradle.kts
  data-local/src/main/java/com/teamdontbe/data_local/SharedPreferenceDataSourceImpl.kt
  data-remote/src/main/java/com/teamdontbe/data_remote/api/HomeApiService.kt
  data-remote/src/main/java/com/teamdontbe/data_remote/datasourceimpl/HomeDataSourceImpl.kt
  data/src/main/java/com/teamdontbe/data/datasource/HomeDataSource.kt
  data/src/main/java/com/teamdontbe/data/datasource/SharedPreferenceDataSource.kt
  data/src/main/java/com/teamdontbe/data/dto/request/RequestComplaintDto.kt
  data/src/main/java/com/teamdontbe/data/dto/request/RequestProfileEditDto.kt
  data/src/main/java/com/teamdontbe/data/repositoryimpl/HomeRepositoryImpl.kt
  data/src/main/java/com/teamdontbe/data/repositoryimpl/LoginRepositoryImpl.kt
  data/src/main/java/com/teamdontbe/data/repositoryimpl/UserInfoRepositoryImpl.kt
  domain/src/main/java/com/teamdontbe/domain/entity/ProfileEditInfoEntity.kt
  domain/src/main/java/com/teamdontbe/domain/repository/HomeRepository.kt
  domain/src/main/java/com/teamdontbe/domain/repository/UserInfoRepository.kt
  feature/src/main/AndroidManifest.xml
  feature/src/main/java/com/teamdontbe/feature/MainActivity.kt
  feature/src/main/java/com/teamdontbe/feature/SplashActivity.kt
  feature/src/main/java/com/teamdontbe/feature/dialog/DeleteWithTitleDialogFragment.kt
  feature/src/main/java/com/teamdontbe/feature/home/HomeBottomSheet.kt
  feature/src/main/java/com/teamdontbe/feature/home/HomeFragment.kt
  feature/src/main/java/com/teamdontbe/feature/home/HomeViewModel.kt
  feature/src/main/java/com/teamdontbe/feature/homedetail/HomeDetailFragment.kt
  feature/src/main/java/com/teamdontbe/feature/mypage/MyPageFragment.kt
  feature/src/main/java/com/teamdontbe/feature/mypage/MyPageViewModel.kt
  feature/src/main/java/com/teamdontbe/feature/mypage/authinfo/MyPagePushAlarmActivity.kt
  feature/src/main/java/com/teamdontbe/feature/mypage/bottomsheet/MyPageAnotherUserBottomSheet.kt
  feature/src/main/java/com/teamdontbe/feature/mypage/bottomsheet/MyPageBottomSheet.kt
  feature/src/main/java/com/teamdontbe/feature/mypage/bottomsheet/MyPageDeleteDialogFragment.kt
  feature/src/main/java/com/teamdontbe/feature/mypage/comment/MyPageCommentFragment.kt
  feature/src/main/java/com/teamdontbe/feature/mypage/feed/MyPageFeedFragment.kt
  feature/src/main/java/com/teamdontbe/feature/signup/SignUpProfileActivity.kt
  feature/src/main/java/com/teamdontbe/feature/signup/SignUpProfileViewModel.kt
  feature/src/main/java/com/teamdontbe/feature/util/KeyStorage.kt
  feature/src/main/res/drawable/ic_push_alarm_setting.xml
  feature/src/main/res/drawable/img_fcm_app_logo.png
  feature/src/main/res/layout/activity_push_alarm.xml
  feature/src/main/res/layout/bottom_sheet_my_page_hamberger.xml
  feature/src/main/res/layout/item_home_comment.xml
  feature/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: ⭐ [FEAT], 🐱 소현

#275 [Fix/#273] : 4차 스프린트 2차 QA 반영
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamdontbe/dontbe/service/DontBeFirebaseMessagingService.kt
  feature/src/main/AndroidManifest.xml
Labels: 🔨 [FIX], 🐱 소현

#276 [Feature/#273] module graph
  build.gradle.kts
  gradle/projectDependencyGraph.gradle
Labels: ⭐ [FEAT]
