Repository TeamDon-tBe/ANDROID, pull requests merged in 2024-02, with the labels that each got.

#180 [Feature/#179] 회원 가입화면 전체선택 수정
  feature/src/main/java/com/teamdontbe/feature/mypage/MyPageFragment.kt
  feature/src/main/java/com/teamdontbe/feature/mypage/comment/MyPageCommentFragment.kt
  feature/src/main/java/com/teamdontbe/feature/mypage/feed/MyPageFeedFragment.kt
  feature/src/main/java/com/teamdontbe/feature/signup/SignUpAgreeActivity.kt
  feature/src/main/java/com/teamdontbe/feature/signup/SignUpProfileActivity.kt
  feature/src/main/java/com/teamdontbe/feature/util/KeyStorage.kt
  feature/src/main/res/layout/activity_sign_up_agree.xml
  feature/src/main/res/layout/view_appbar_with_back.xml
Labels: 🔨 [FIX], 🐻 찬우

#182 [Feature/#178] refactoring
  feature/src/main/java/com/teamdontbe/feature/MainActivity.kt
  feature/src/main/java/com/teamdontbe/feature/dialog/PostingRestrictionDialogFragment.kt
  feature/src/main/java/com/teamdontbe/feature/notification/NotificationFragment.kt
  feature/src/main/java/com/teamdontbe/feature/posting/PostingFragment.kt
  feature/src/main/res/drawable/shape_primary_fill_left10_rect.xml
  feature/src/main/res/drawable/shape_primary_fill_right10_rect.xml
  feature/src/main/res/layout/activity_example.xml
  feature/src/main/res/layout/activity_sign_up_profile.xml
  feature/src/main/res/layout/bottomsheet_comment.xml
  feature/src/main/res/layout/fragment_posting.xml
  feature/src/main/res/values/themes.xml
Labels: 🐰 언지,  ♻️ [REFACTOR]

#187 [Feature/#186] qa fix
  feature/src/main/java/com/teamdontbe/feature/notification/NotificationViewModel.kt
  feature/src/main/java/com/teamdontbe/feature/posting/PostingFragment.kt
  feature/src/main/res/layout/fragment_posting.xml
Labels: ⭐ [FEAT], 🐰 언지

#189 [Feature/#184] 프로필 수정 화면 fix
  data/src/main/java/com/teamdontbe/data/dto/request/RequestProfileEditDto.kt
  data/src/main/java/com/teamdontbe/data/repositoryimpl/LoginRepositoryImpl.kt
  domain/src/main/java/com/teamdontbe/domain/repository/LoginRepository.kt
  feature/src/main/AndroidManifest.xml
  feature/src/main/java/com/teamdontbe/feature/ErrorActivity.kt
  feature/src/main/java/com/teamdontbe/feature/mypage/MyPageFragment.kt
  feature/src/main/java/com/teamdontbe/feature/mypage/MyPageViewModel.kt
  feature/src/main/java/com/teamdontbe/feature/mypage/comment/MyPageCommentFragment.kt
  feature/src/main/java/com/teamdontbe/feature/mypage/feed/MyPageFeedFragment.kt
  feature/src/main/java/com/teamdontbe/feature/signup/SignUpAgreeActivity.kt
  feature/src/main/java/com/teamdontbe/feature/signup/SignUpProfileActivity.kt
  feature/src/main/java/com/teamdontbe/feature/signup/SignUpProfileViewModel.kt
  feature/src/main/java/com/teamdontbe/feature/signup/UserProfileModel.kt
  feature/src/main/res/layout/activity_sign_up_profile.xml
  feature/src/main/res/layout/bottom_sheet_my_page_hamberger.xml
  feature/src/main/res/values/strings.xml
Labels: 🔨 [FIX], 🐻 찬우

#193 [Hotfix/#190] : fix kakologin
  feature/src/main/AndroidManifest.xml
  feature/src/main/java/com/teamdontbe/feature/login/LoginActivity.kt
Labels: 🚑️ [HOTFIX], 🐱 소현

#197 #188 [MOD] : key storage 파일로 상수 export
  feature/src/main/java/com/teamdontbe/feature/home/HomeFragment.kt
  feature/src/main/java/com/teamdontbe/feature/homedetail/HomeDetailFragment.kt
  feature/src/main/java/com/teamdontbe/feature/mypage/authwithdraw/MyPageAuthWithdrawGuideActivity.kt
  feature/src/main/java/com/teamdontbe/feature/mypage/authwithdraw/MyPageAuthWithdrawReasonActivity.kt
  feature/src/main/java/com/teamdontbe/feature/mypage/comment/MyPageCommentFragment.kt
  feature/src/main/java/com/teamdontbe/feature/mypage/feed/MyPageFeedFragment.kt
  feature/src/main/java/com/teamdontbe/feature/notification/NotificationFragment.kt
  feature/src/main/java/com/teamdontbe/feature/posting/PostingFragment.kt
  feature/src/main/java/com/teamdontbe/feature/util/KeyStorage.kt
Labels: ✅ [MOD], 🐰 언지

#198 [Feature/#192] 로딩뷰 구현
  feature/build.gradle.kts
  feature/src/main/AndroidManifest.xml
  feature/src/main/java/com/teamdontbe/feature/LoadingActivity.kt
  feature/src/main/java/com/teamdontbe/feature/home/HomeFragment.kt
  feature/src/main/java/com/teamdontbe/feature/mypage/authwithdraw/MyPageAuthWithdrawGuideActivity.kt
  feature/src/main/java/com/teamdontbe/feature/notification/NotificationFragment.kt
  feature/src/main/res/anim/anim_swipe_refresh_slide_down.xml
  feature/src/main/res/anim/anim_swipe_refresh_slide_up.xml
  feature/src/main/res/drawable/img_my_page_auth_withdraw_guide.xml
  feature/src/main/res/drawable/shape_gray02_fill_4_rect.xml
  feature/src/main/res/drawable/shape_gray02_line_10_rect.xml
  feature/src/main/res/layout/activity_loading.xml
  feature/src/main/res/layout/activity_my_page_auth_withdraw_guide.xml
  feature/src/main/res/layout/fragment_delete_complete_dialog.xml
  feature/src/main/res/raw/lottie_loading.json
  feature/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: 💟 [UI], 🐰 언지

#199 [Feature/#181] : refresh fix
  app/src/main/java/com/teamdontbe/dontbe/interceptor/TokenInterceptor.kt
  data-local/src/main/java/com/teamdontbe/data_local/SharedPreferenceDataSourceImpl.kt
  data/src/main/java/com/teamdontbe/data/datasource/SharedPreferenceDataSource.kt
  data/src/main/java/com/teamdontbe/data/repositoryimpl/UserInfoRepositoryImpl.kt
  domain/src/main/java/com/teamdontbe/domain/repository/UserInfoRepository.kt
  feature/src/main/java/com/teamdontbe/feature/MainActivity.kt
  feature/src/main/java/com/teamdontbe/feature/SplashActivity.kt
  feature/src/main/java/com/teamdontbe/feature/home/HomeViewModel.kt
  feature/src/main/java/com/teamdontbe/feature/login/LoginActivity.kt
  feature/src/main/java/com/teamdontbe/feature/notification/NotificationViewModel.kt
  feature/src/main/java/com/teamdontbe/feature/onboarding/OnboardingFragment.kt
  feature/src/main/java/com/teamdontbe/feature/onboarding/OnboardingViewModel.kt
  feature/src/main/res/layout/item_home_comment.xml
  feature/src/main/res/layout/item_home_feed.xml
  feature/src/main/res/layout/item_my_page_comment.xml
  feature/src/main/res/values-night/themes.xml
  feature/src/main/res/values/themes.xml
  gradle/libs.versions.toml
Labels: 🔨 [FIX], 🐱 소현

#201 [Feature/#200] 계정 삭제 API 연결
  app/src/main/java/com/teamdontbe/dontbe/di/WithdrawModule.kt
  data-remote/src/main/java/com/teamdontbe/data_remote/api/WithdrawApiService.kt
  data-remote/src/main/java/com/teamdontbe/data_remote/datasourceimpl/WithdrawDataSourceImpl.kt
  data/src/main/java/com/teamdontbe/data/datasource/WithdrawDataSource.kt
  data/src/main/java/com/teamdontbe/data/dto/request/RequestWithdrawDto.kt
  data/src/main/java/com/teamdontbe/data/repositoryimpl/WithdrawRepositoryImpl.kt
  domain/src/main/java/com/teamdontbe/domain/repository/WithdrawRepository.kt
  feature/src/main/java/com/teamdontbe/feature/dialog/DeleteWithTitleWideDialogFragment.kt
  feature/src/main/java/com/teamdontbe/feature/mypage/MyPageViewModel.kt
  feature/src/main/java/com/teamdontbe/feature/mypage/authwithdraw/MyPageAuthWithdrawGuideActivity.kt
  feature/src/main/java/com/teamdontbe/feature/mypage/authwithdraw/MyPageAuthWithdrawReasonActivity.kt
  feature/src/main/java/com/teamdontbe/feature/mypage/authwithdraw/MyPageAuthWithdrawViewModel.kt
  feature/src/main/java/com/teamdontbe/feature/mypage/bottomsheet/MyPageBottomSheet.kt
  feature/src/main/java/com/teamdontbe/feature/util/KeyStorage.kt
Labels: ⭐ [FEAT], 🐰 언지

#206 [FIX/#205] : feed dto 수정
  data/src/main/java/com/teamdontbe/data/dto/response/ResponseFeedDto.kt
  domain/src/main/java/com/teamdontbe/domain/entity/FeedEntity.kt
  feature/src/main/java/com/teamdontbe/feature/home/Feed.kt
Labels: 🔨 [FIX], 🐱 소현

#211 [Feature/#203] noti 페이지네이션 적용
  data-remote/src/main/java/com/teamdontbe/data_remote/api/NotificationApiService.kt
  data-remote/src/main/java/com/teamdontbe/data_remote/datasourceimpl/NotificationDataSourceImpl.kt
  data-remote/src/main/java/com/teamdontbe/data_remote/pagingsourceimpl/NotificationPagingSourceImpl.kt
  data/src/main/java/com/teamdontbe/data/datasource/NotificationDataSource.kt
  data/src/main/java/com/teamdontbe/data/dto/response/ResponseNotificationListDto.kt
  data/src/main/java/com/teamdontbe/data/repositoryimpl/NotificationRepositoryImpl.kt
  domain/src/main/java/com/teamdontbe/domain/entity/NotiEntity.kt
  domain/src/main/java/com/teamdontbe/domain/repository/NotificationRepository.kt
  feature/src/main/java/com/teamdontbe/feature/notification/NotificationFragment.kt
  feature/src/main/java/com/teamdontbe/feature/notification/NotificationViewModel.kt
  feature/src/main/java/com/teamdontbe/feature/notification/adapter/NotificationPagingAdapter.kt
  feature/src/main/java/com/teamdontbe/feature/notification/adapter/NotificationViewHolder.kt
  feature/src/main/res/layout/activity_sign_up_profile.xml
  feature/src/main/res/values/themes.xml
Labels: ⭐ [FEAT], 🐰 언지

#212 [Feature/#210] 로딩뷰 초 설정 및 애니메이션 적용
  feature/src/main/AndroidManifest.xml
  feature/src/main/java/com/teamdontbe/feature/LoadingActivity.kt
  feature/src/main/res/anim/anim_loading_fade_out.xml
  feature/src/main/res/layout/activity_loading.xml
  feature/src/main/res/values/themes.xml
Labels: ⭐ [FEAT], 🐰 언지

#207 [Feature/#196] 멀티파트 통신
  data-remote/src/main/java/com/teamdontbe/data_remote/api/LoginApiService.kt
  data-remote/src/main/java/com/teamdontbe/data_remote/datasourceimpl/LoginDataSourceImpl.kt
  data/src/main/java/com/teamdontbe/data/datasource/LoginDataSource.kt
  data/src/main/java/com/teamdontbe/data/repositoryimpl/LoginRepositoryImpl.kt
  data/src/main/java/com/teamdontbe/data/repositoryimpl/MyPageRepositoryImpl.kt
  domain/src/main/java/com/teamdontbe/domain/entity/ProfileEditInfoEntity.kt
  domain/src/main/java/com/teamdontbe/domain/repository/LoginRepository.kt
  domain/src/main/java/com/teamdontbe/domain/repository/MyPageRepository.kt
  feature/src/main/AndroidManifest.xml
  feature/src/main/java/com/teamdontbe/feature/mypage/MyPageFragment.kt
  feature/src/main/java/com/teamdontbe/feature/mypage/MyPageViewModel.kt
  feature/src/main/java/com/teamdontbe/feature/mypage/bottomsheet/MyPageBottomSheet.kt
  feature/src/main/java/com/teamdontbe/feature/mypage/feed/MyPageFeedFragment.kt
  feature/src/main/java/com/teamdontbe/feature/onboarding/OnboardingFragment.kt
  feature/src/main/java/com/teamdontbe/feature/onboarding/OnboardingViewModel.kt
  feature/src/main/java/com/teamdontbe/feature/posting/PostingViewModel.kt
  feature/src/main/java/com/teamdontbe/feature/signup/SignUpAgreeActivity.kt
  feature/src/main/java/com/teamdontbe/feature/signup/SignUpProfileActivity.kt
  feature/src/main/java/com/teamdontbe/feature/signup/SignUpProfileViewModel.kt
  feature/src/main/res/layout/activity_sign_up_agree.xml
  feature/src/main/res/layout/activity_sign_up_profile.xml
  feature/src/main/res/layout/item_home_feed.xml
Labels: ⭐ [FEAT], 🐻 찬우

#219 [Feature/#209] : comment pagination
  data-remote/src/main/java/com/teamdontbe/data_remote/api/HomeApiService.kt
  data-remote/src/main/java/com/teamdontbe/data_remote/datasourceimpl/HomeDataSourceImpl.kt
  data-remote/src/main/java/com/teamdontbe/data_remote/pagingsourceimpl/HomeCommentPagingSourceImpl.kt
  data-remote/src/main/java/com/teamdontbe/data_remote/pagingsourceimpl/HomeFeedPagingSourceImpl.kt
  data/src/main/java/com/teamdontbe/data/datasource/HomeDataSource.kt
  data/src/main/java/com/teamdontbe/data/dto/response/ResponseCommentDto.kt
  data/src/main/java/com/teamdontbe/data/repositoryimpl/HomeRepositoryImpl.kt
  data/src/main/java/com/teamdontbe/data/repositoryimpl/UserInfoRepositoryImpl.kt
  domain/src/main/java/com/teamdontbe/domain/entity/CommentEntity.kt
  domain/src/main/java/com/teamdontbe/domain/repository/HomeRepository.kt
  domain/src/main/java/com/teamdontbe/domain/repository/UserInfoRepository.kt
  feature/src/main/java/com/teamdontbe/feature/MainActivity.kt
  feature/src/main/java/com/teamdontbe/feature/dialog/DeleteWithTitleWideDialogFragment.kt
  feature/src/main/java/com/teamdontbe/feature/home/HomeFragment.kt
  feature/src/main/java/com/teamdontbe/feature/home/HomeViewModel.kt
  feature/src/main/java/com/teamdontbe/feature/home/viewholder/HomeFeedViewHolder.kt
  feature/src/main/java/com/teamdontbe/feature/homedetail/HomeDetailFragment.kt
  feature/src/main/java/com/teamdontbe/feature/homedetail/HomeDetailPagingCommentAdapter.kt
  feature/src/main/java/com/teamdontbe/feature/homedetail/viewholder/HomeDetailCommentViewHolder.kt
  feature/src/main/java/com/teamdontbe/feature/login/LoginActivity.kt
  feature/src/main/java/com/teamdontbe/feature/mypage/authwithdraw/MyPageAuthWithdrawViewModel.kt
  feature/src/main/java/com/teamdontbe/feature/onboarding/OnboardingFragment.kt
  feature/src/main/res/layout/bottomsheet_comment.xml
  feature/src/main/res/layout/fragment_home_detail.xml
  feature/src/main/res/layout/item_home_feed.xml
  feature/src/main/res/navigation/nav_main.xml
Labels: ⭐ [FEAT], 🔨 [FIX], 🐱 소현

#218 [Feature/#208] 마이페이지 페이징 + 바텀네비 아이콘 오류 수정
  data-remote/src/main/java/com/teamdontbe/data_remote/api/MyPageApiService.kt
  data-remote/src/main/java/com/teamdontbe/data_remote/datasourceimpl/MyPageDataSourceImpl.kt
  data-remote/src/main/java/com/teamdontbe/data_remote/pagingsourceimpl/MyPageCommentPagingSourceImpl.kt
  data-remote/src/main/java/com/teamdontbe/data_remote/pagingsourceimpl/MyPageFeedPagingSourceImpl.kt
  data/src/main/java/com/teamdontbe/data/datasource/MyPageDataSource.kt
  data/src/main/java/com/teamdontbe/data/repositoryimpl/MyPageRepositoryImpl.kt
  domain/src/main/java/com/teamdontbe/domain/repository/MyPageRepository.kt
  feature/src/main/java/com/teamdontbe/feature/MainActivity.kt
  feature/src/main/java/com/teamdontbe/feature/mypage/MyPageFragment.kt
  feature/src/main/java/com/teamdontbe/feature/mypage/MyPageViewModel.kt
  feature/src/main/java/com/teamdontbe/feature/mypage/bottomsheet/MyPageDeleteDialogFragment.kt
  feature/src/main/java/com/teamdontbe/feature/mypage/comment/MyPageCommentAdapter.kt
  feature/src/main/java/com/teamdontbe/feature/mypage/comment/MyPageCommentFragment.kt
  feature/src/main/java/com/teamdontbe/feature/mypage/comment/MyPageCommentViewHolder.kt
  feature/src/main/java/com/teamdontbe/feature/mypage/comment/MyPageCommentViewModel.kt
  feature/src/main/java/com/teamdontbe/feature/mypage/feed/MyPageFeedAdapter.kt
  feature/src/main/java/com/teamdontbe/feature/mypage/feed/MyPageFeedFragment.kt
  feature/src/main/java/com/teamdontbe/feature/mypage/feed/MyPageFeedViewHolder.kt
  feature/src/main/java/com/teamdontbe/feature/mypage/feed/MyPageFeedViewModel.kt
  feature/src/main/java/com/teamdontbe/feature/signup/SignUpProfileActivity.kt
  feature/src/main/res/layout/fragment_my_page.xml
  feature/src/main/res/navigation/nav_main.xml
Labels: ⭐ [FEAT], 🐻 찬우

#221 [Feature/#220] posting qa fix
  feature/src/main/java/com/teamdontbe/feature/posting/PostingFragment.kt
  feature/src/main/res/values/themes.xml
Labels: 🔨 [FIX], 🐰 언지
