Repository TeamDon-tBe/ANDROID, pull requests merged in 2024-03, with the labels that each got.

#224 [Feature/#223] qa fix
  feature/src/main/java/com/teamdontbe/feature/LoadingActivity.kt
  feature/src/main/res/drawable/shape_primary_fill_circle.xml
  feature/src/main/res/layout/fragment_notification.xml
  feature/src/main/res/layout/item_notification_feed.xml
  feature/src/main/res/values/themes.xml
Labels: 🔨 [FIX], 🐰 언지

#226 Feature/#225 1st sprint qa
  core-ui/src/main/java/com/teamdontbe/core_ui/view/ClickListenerExt.kt
  core-ui/src/main/java/com/teamdontbe/core_ui/view/DuplicateBlockClickListener.kt
  data-remote/src/main/java/com/teamdontbe/data_remote/pagingsourceimpl/HomeCommentPagingSourceImpl.kt
  data/src/main/java/com/teamdontbe/data/repositoryimpl/HomeRepositoryImpl.kt
  domain/src/main/java/com/teamdontbe/domain/repository/HomeRepository.kt
  feature/src/main/java/com/teamdontbe/feature/ErrorActivity.kt
  feature/src/main/java/com/teamdontbe/feature/MainActivity.kt
  feature/src/main/java/com/teamdontbe/feature/dialog/DeleteDialogFragment.kt
  feature/src/main/java/com/teamdontbe/feature/dialog/DeleteWithTitleDialogFragment.kt
  feature/src/main/java/com/teamdontbe/feature/home/HomeBottomSheet.kt
  feature/src/main/java/com/teamdontbe/feature/home/HomeFragment.kt
  feature/src/main/java/com/teamdontbe/feature/home/HomeViewModel.kt
  feature/src/main/java/com/teamdontbe/feature/home/viewholder/HomeFeedViewHolder.kt
  feature/src/main/java/com/teamdontbe/feature/homedetail/CommentBottomSheet.kt
  feature/src/main/java/com/teamdontbe/feature/homedetail/DeleteDialogListener.kt
  feature/src/main/java/com/teamdontbe/feature/homedetail/HomeDetailFragment.kt
  feature/src/main/java/com/teamdontbe/feature/homedetail/viewholder/HomeDetailCommentViewHolder.kt
  feature/src/main/java/com/teamdontbe/feature/mypage/MyPageViewModel.kt
  feature/src/main/java/com/teamdontbe/feature/snackbar/UploadingSnackBar.kt
  feature/src/main/java/com/teamdontbe/feature/util/KeyStorage.kt
  feature/src/main/res/drawable/sel_home_heart.xml
  feature/src/main/res/layout/bottomsheet_comment.xml
  feature/src/main/res/layout/fragment_home_detail.xml
  feature/src/main/res/values/strings.xml
Labels: 🔨 [FIX], 🐱 소현

#227 [Feature/#217] qa fix
  core-ui/src/main/java/com/teamdontbe/core_ui/util/fragment/FragmentExt.kt
  feature/src/main/java/com/teamdontbe/feature/mypage/MyPageFragment.kt
  feature/src/main/java/com/teamdontbe/feature/mypage/MyPageViewModel.kt
  feature/src/main/java/com/teamdontbe/feature/mypage/bottomsheet/MyPageAnotherUserBottomSheet.kt
  feature/src/main/java/com/teamdontbe/feature/mypage/comment/MyPageCommentFragment.kt
  feature/src/main/java/com/teamdontbe/feature/mypage/feed/MyPageFeedFragment.kt
  feature/src/main/java/com/teamdontbe/feature/onboarding/OnboardingFragment.kt
  feature/src/main/java/com/teamdontbe/feature/signup/SignUpProfileActivity.kt
  feature/src/main/res/layout/fragment_my_page.xml
Labels: 🚑️ [HOTFIX], 🐻 찬우

#229 [#228/FIIX] : bottom navi 이슈 해결
  feature/src/main/java/com/teamdontbe/feature/MainActivity.kt
Labels: 🔨 [FIX], 🐱 소현

#231 [Feature/#230] : home detail api v2
  data-remote/src/main/java/com/teamdontbe/data_remote/api/HomeApiService.kt
  feature/src/main/java/com/teamdontbe/feature/homedetail/HomeDetailFragment.kt
  feature/src/main/res/navigation/nav_main.xml
Labels: ⭐ [FEAT], 🐱 소현

#234 [Hotfix/#232] paging empty view
  data-remote/src/main/java/com/teamdontbe/data_remote/datasourceimpl/MyPageDataSourceImpl.kt
  data-remote/src/main/java/com/teamdontbe/data_remote/pagingsourceimpl/MyPageCommentPagingSourceImpl.kt
  data/src/main/java/com/teamdontbe/data/datasource/MyPageDataSource.kt
  data/src/main/java/com/teamdontbe/data/dto/response/ResponseMyPageCommentDto.kt
  data/src/main/java/com/teamdontbe/data/repositoryimpl/MyPageRepositoryImpl.kt
  domain/src/main/java/com/teamdontbe/domain/entity/CommentEntity.kt
  domain/src/main/java/com/teamdontbe/domain/entity/MyPageCommentEntity.kt
  domain/src/main/java/com/teamdontbe/domain/repository/MyPageRepository.kt
  feature/src/main/java/com/teamdontbe/feature/mypage/MyPageFragment.kt
  feature/src/main/java/com/teamdontbe/feature/mypage/MyPageViewModel.kt
  feature/src/main/java/com/teamdontbe/feature/mypage/comment/MyPageCommentAdapter.kt
  feature/src/main/java/com/teamdontbe/feature/mypage/comment/MyPageCommentFragment.kt
  feature/src/main/java/com/teamdontbe/feature/mypage/comment/MyPageCommentViewHolder.kt
  feature/src/main/java/com/teamdontbe/feature/mypage/feed/MyPageFeedFragment.kt
  feature/src/main/res/layout/fragment_my_page_comment.xml
  feature/src/main/res/layout/item_my_page_comment.xml
  feature/src/main/res/values/strings.xml
Labels: 🚑️ [HOTFIX], 🐻 찬우

#237 [Fix/#236] qa fix
  feature/src/main/res/values/strings.xml
Labels: 🔨 [FIX], 💟 [UI], 🐰 언지

#238 [Feature/#233] : 최종 Qa
  data/src/main/java/com/teamdontbe/data/repositoryimpl/LoginRepositoryImpl.kt
  domain/src/main/java/com/teamdontbe/domain/repository/LoginRepository.kt
  feature/src/main/java/com/teamdontbe/feature/login/LoginActivity.kt
  feature/src/main/java/com/teamdontbe/feature/login/LoginViewModel.kt
  feature/src/main/res/values/strings.xml
  feature/src/main/res/values/textappearances.xml
Labels: 🔨 [FIX], 🐱 소현

#239 [Hotfix/#235] api레벨에 따라 포토피커/갤러리 퍼미션 수정
  feature/src/main/java/com/teamdontbe/feature/signup/SignUpProfileActivity.kt
  feature/src/main/res/layout/activity_sign_up_agree.xml
  feature/src/main/res/values/strings.xml
Labels: ⭐ [FEAT], 🚑️ [HOTFIX], 🐻 찬우

#241 [Hotfix/#240] 마이페이지 투명도 오류 수정 + 전체 텍스트 사이즈 수정
  feature/src/main/java/com/teamdontbe/feature/mypage/bottomsheet/MyPageTransparentDialogFragment.kt
  feature/src/main/java/com/teamdontbe/feature/mypage/comment/MyPageCommentFragment.kt
  feature/src/main/java/com/teamdontbe/feature/mypage/feed/MyPageFeedFragment.kt
  feature/src/main/res/values/textappearances.xml
Labels: 🔨 [FIX], 🐻 찬우

#244 [Fix/#233] 1.0.0 업뎃 전 버전 코드 변경, 슬랙 디자인 qa 반영
  domain/src/main/java/com/teamdontbe/domain/entity/CommentEntity.kt
  domain/src/main/java/com/teamdontbe/domain/entity/FeedEntity.kt
  feature/src/main/java/com/teamdontbe/feature/home/HomeFragment.kt
  feature/src/main/java/com/teamdontbe/feature/home/viewholder/HomeFeedViewHolder.kt
  feature/src/main/java/com/teamdontbe/feature/homedetail/HomeDetailFragment.kt
  feature/src/main/java/com/teamdontbe/feature/homedetail/viewholder/HomeDetailCommentViewHolder.kt
  feature/src/main/java/com/teamdontbe/feature/mypage/comment/MyPageCommentFragment.kt
  feature/src/main/java/com/teamdontbe/feature/mypage/comment/MyPageCommentViewHolder.kt
  feature/src/main/java/com/teamdontbe/feature/mypage/feed/MyPageFeedFragment.kt
  feature/src/main/java/com/teamdontbe/feature/mypage/feed/MyPageFeedViewHolder.kt
  feature/src/main/res/layout/activity_login.xml
  feature/src/main/res/layout/fragment_transparent_dialog.xml
  feature/src/main/res/layout/item_home_comment.xml
  feature/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: 🔨 [FIX], 🐱 소현
